export const bibleVerses = [
  "For God so loved the world that He gave His one and only Son, that whoever believes in Him shall not perish but have eternal life. - John 3:16",
  "The Lord is my shepherd, I shall not want. - Psalm 23:1",
  "I can do all things through Christ who strengthens me. - Philippians 4:13",
  "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go. - Joshua 1:9",
  "Cast all your anxiety on Him because He cares for you. - 1 Peter 5:7",
  "The Lord is close to the brokenhearted and saves those who are crushed in spirit. - Psalm 34:18",
  "Trust in the Lord with all your heart and lean not on your own understanding. - Proverbs 3:5",
  "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid? - Psalm 27:1",
  "Come to me, all you who are weary and burdened, and I will give you rest. - Matthew 11:28",
  "God is our refuge and strength, an ever-present help in trouble. - Psalm 46:1",
  "Do not be overcome by evil, but overcome evil with good. - Romans 12:21",
  "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you. - Zephaniah 3:17",
  "My grace is sufficient for you, for My power is made perfect in weakness. - 2 Corinthians 12:9",
  "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. - Galatians 6:9",
  "You will keep in perfect peace those whose minds are steadfast, because they trust in You. - Isaiah 26:3",
  "Fear not, for I am with you; be not dismayed, for I am your God. - Isaiah 41:10",
  "The Lord will fight for you; you need only to be still. - Exodus 14:14",
  "The joy of the Lord is your strength. - Nehemiah 8:10",
  "And we know that in all things God works for the good of those who love Him. - Romans 8:28",
  "The name of the Lord is a strong tower; the righteous run to it and are safe. - Proverbs 18:10",
  "Blessed is the one who trusts in the Lord. - Jeremiah 17:7",
  "The peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. - Philippians 4:7",
  "When you pass through the waters, I will be with you. - Isaiah 43:2",
  "I sought the Lord, and He answered me; He delivered me from all my fears. - Psalm 34:4",
  "Do everything in love. - 1 Corinthians 16:14",
  "Be joyful in hope, patient in affliction, faithful in prayer. - Romans 12:12",
  "The steadfast love of the Lord never ceases; His mercies never come to an end. - Lamentations 3:22",
  "If God is for us, who can be against us? - Romans 8:31",
  "Draw near to God and He will draw near to you. - James 4:8",
  "The Lord is faithful, and He will strengthen you and protect you from the evil one. - 2 Thessalonians 3:3",
  "The Lord bless you and keep you; the Lord make His face shine on you and be gracious to you. - Numbers 6:24-25",
  "In this world you will have trouble. But take heart! I have overcome the world. - John 16:33",
  "But those who hope in the Lord will renew their strength. They will soar on wings like eagles. - Isaiah 40:31",
  "I lift up my eyes to the hills—where does my help come from? My help comes from the Lord. - Psalm 121:1-2",
  "You are the light of the world. A city on a hill cannot be hidden. - Matthew 5:14",
  "The Lord is good, a refuge in times of trouble. - Nahum 1:7",
  "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you. - Jeremiah 29:11",
  "Do not grieve, for the joy of the Lord is your strength. - Nehemiah 8:10",
  "Let the peace of Christ rule in your hearts. - Colossians 3:15",
  "The Lord upholds all who fall and lifts up all who are bowed down. - Psalm 145:14",
  "Rejoice in the Lord always. I will say it again: Rejoice! - Philippians 4:4",
  "Do not fear, for I have redeemed you; I have summoned you by name; you are mine. - Isaiah 43:1",
  "The Lord is near to all who call on Him. - Psalm 145:18",
  "With God all things are possible. - Matthew 19:26",
  "Your word is a lamp to my feet and a light to my path. - Psalm 119:105",
  "I will never leave you nor forsake you. - Hebrews 13:5",
  "Let everything that has breath praise the Lord. - Psalm 150:6",
  "The Lord gives strength to His people; the Lord blesses His people with peace. - Psalm 29:11",
  "He heals the brokenhearted and binds up their wounds. - Psalm 147:3",
  "Therefore encourage one another and build each other up. - 1 Thessalonians 5:11",
  "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. - Philippians 4:6",
  "The Lord is my strength and my song; He has given me victory. - Exodus 15:2",
  "The Lord will keep you from all harm—He will watch over your life. - Psalm 121:7",
  "The Lord is righteous in all His ways and loving toward all He has made. - Psalm 145:17",
  "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven. - Matthew 5:16",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline. - 2 Timothy 1:7",
  "Blessed are the pure in heart, for they will see God. - Matthew 5:8",
  "Do not let your hearts be troubled. You believe in God; believe also in Me. - John 14:1",
  "He gives power to the weak and strength to the powerless. - Isaiah 40:29",
  "The Lord your God goes with you; He will never leave you nor forsake you. - Deuteronomy 31:6",
  "Wait for the Lord; be strong and take heart and wait for the Lord. - Psalm 27:14",
  "As for God, His way is perfect: The Lord’s word is flawless; He shields all who take refuge in Him. - Psalm 18:30",
  "May the God of hope fill you with all joy and peace as you trust in Him. - Romans 15:13",
  "Do not be afraid of them; the Lord your God Himself will fight for you. - Deuteronomy 3:22",
  "The Lord is gracious and compassionate, slow to anger and rich in love. - Psalm 145:8",
  "Let the morning bring me word of Your unfailing love, for I have put my trust in You. - Psalm 143:8",
  "Be still before the Lord and wait patiently for Him. - Psalm 37:7",
  "The eternal God is your refuge, and underneath are the everlasting arms. - Deuteronomy 33:27",
  "He alone is my rock and my salvation; He is my fortress, I will not be shaken. - Psalm 62:6",
  "You, Lord, are forgiving and good, abounding in love to all who call to You. - Psalm 86:5",
  "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. - Romans 12:2",
  "Even though I walk through the darkest valley, I will fear no evil, for You are with me. - Psalm 23:4",
  "The Lord is my portion; therefore I will wait for Him. - Lamentations 3:24",
  "Blessed are those who hunger and thirst for righteousness, for they will be filled. - Matthew 5:6",
  "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness. - Galatians 5:22",
  "Cast your cares on the Lord and He will sustain you. - Psalm 55:22",
  "The Lord gives wisdom; from His mouth come knowledge and understanding. - Proverbs 2:6",
  "He will cover you with His feathers, and under His wings you will find refuge. - Psalm 91:4",
  "Blessed are those who take refuge in Him. - Psalm 34:8",
  "So do not fear, for I am with you; do not be dismayed, for I am your God. - Isaiah 41:10",
  "Commit to the Lord whatever you do, and He will establish your plans. - Proverbs 16:3",
  "Do not fear, little flock, for it is your Father’s good pleasure to give you the kingdom. - Luke 12:32",
  "The Lord will guide you always; He will satisfy your needs in a sun-scorched land. - Isaiah 58:11",
  "Let us hold unswervingly to the hope we profess, for He who promised is faithful. - Hebrews 10:23",
  "He gives strength to the weary and increases the power of the weak. - Isaiah 40:29",
  "The Lord is compassionate and gracious, slow to anger, abounding in love. - Psalm 103:8",
  "When I am afraid, I put my trust in You. - Psalm 56:3",
  "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord. - Romans 6:23",
  "So if the Son sets you free, you will be free indeed. - John 8:36",
  "Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life. - James 1:12",
  "The Lord is good to those whose hope is in Him, to the one who seeks Him. - Lamentations 3:25",
  "I have set the Lord always before me. Because He is at my right hand, I will not be shaken. - Psalm 16:8",
  "Do not be afraid; you are worth more than many sparrows. - Matthew 10:31",
  "I have told you these things, so that in Me you may have peace. - John 16:33",
  "He who dwells in the shelter of the Most High will rest in the shadow of the Almighty. - Psalm 91:1",
  "For the Lord your God is a merciful God; He will not abandon or destroy you. - Deuteronomy 4:31",
  "The Lord your God will bless you in everything you do. - Deuteronomy 15:10",
  "My flesh and my heart may fail, but God is the strength of my heart and my portion forever. - Psalm 73:26"
]
